### ISSUE TITLE
"undefined method `Exit' for nil:NilClass" when using em-synchrony on Ubuntu

### ISSUE THREAD

**Issue by alexkwolfe** [rubyjs/therubyracer#206]
This occurs for me on Ubuntu 10.04.4 LTS, but not on Mountain Lion. I'm using libv8 3.11.8.3 and the latest commit from therubyracer repo (e31dc5c) master branch.

The test case provided in the potentially related issue #190 executes fine on both operating systems.

The following test case, however, does not.  It passes on Mountain Lion, but fails on Ubuntu.

At first I thought maybe this was a problem with Fibers. I know that's a point of difficulty. But if you comment out the `test_first` method, the `test_second` method executes without error.  Also, the fact that the test passes on Mountain Lion but not Ubuntu seems like a clue.

I can most likely provide access to the environment where this fails, if that helps.

``` ruby
require 'test/unit'
require 'v8'
require 'eventmachine-le'
require 'em-synchrony'

class RacerTest < Test::Unit::TestCase
  def do_eval
    fxn = V8::Context.new.eval('(function(arg) { return 1 + arg })')
    assert_equal 6, fxn.call(5)
  end

  def test_first
    do_eval
  end

  def test_second
    EM.synchrony {
      begin
        do_eval
      ensure
        EM.stop
      end
    }
  end
end
```

Here's what the error on Ubuntu looks like:

```
$ bundle exec ruby -Itest test/unit/rr_test.rb 
Loaded suite test/unit/rr_test
Started
.E
===============================================================================
Error: test_second(RacerTest)
  NoMethodError: undefined method `Exit' for nil:NilClass
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:237:in `ensure in block (2 levels) in lock_scope_and_enter'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:237:in `block (2 levels) in lock_scope_and_enter'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:232:in `call'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:232:in `HandleScope'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:232:in `block in lock_scope_and_enter'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:231:in `call'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:231:in `Locker'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:231:in `lock_scope_and_enter'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:191:in `enter'
../bundler/gems/therubyracer-e31dc5c0042e/lib/v8/context.rb:85:in `eval'
test/unit/rr_test.rb:9:in `do_eval'
test/unit/rr_test.rb:20:in `block in test_second'
../gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `call'
../gems/em-synchrony-1.0.2/lib/em-synchrony.rb:26:in `block (2 levels) in synchrony'
===============================================================================


Finished in 0.00657601 seconds.

2 tests, 1 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
```

**Comment by bdmac** [comment]
Any update on this issue? I'm hitting this within my sidekiq workers and even using `V8::Locker` does not help. None of the order-dependent repros above matter on our system. Just immediately running `p Fiber.new { V8::C::Locker() {V8::C::Context::New()} }.resume` as the first thing done in my Rails console results in nil being returned.

**Comment by SamSaffron** [comment]
@bdmac see what we do in Discourse,

https://github.com/discourse/discourse/blob/master/app/jobs/base.rb#L148

I think the best thing here (so you avoid this monster of a hack) is to launch sidekiq in a mode where it does not use fibers at all cc @mperham

**Comment by bdmac** [comment]
Will take a look. Short term solution was to spin up a Resque worker for where I am compiling handlebars templates in the background.

**Comment by bdmac** [comment]
@samsaffron I actually tried wrapping the handlebars compilation bit in a thread like you are doing there and also in a sub process with `Process.new {}` but neither of those seemed to really work maybe because I was already in a fiber on sidekiq?

**Comment by SamSaffron** [comment]
It works 100% fine, once you create the new thread you kick out of the
fiber, gist of the code you were using?

**Comment by bdmac** [comment]
Hmm that's what I was expecting to happen as well. It was getting late on Friday though so maybe I was testing something wrong. Will try that again tomorrow.

**Comment by bdmac** [comment]
@SamSaffron so I was going back and looking at what I was trying and this seems to be a minimal failure case for us. This only fails in our EC2 staging environment, not on my local OSX:

```
irb(main):006:0* Thread.new {c=V8::C::Context::New();c.Enter();c.Exit();c}.join
NoMethodError: undefined method `Enter' for nil:NilClass
	from (irb):6:in `block in irb_binding'
```

versus locally:

```
irb(main):009:0> Thread.new {c=V8::C::Context::New();c.Enter();c.Exit();c}.join.value
=> #<V8::C::Context:0x007fff3aece050>
```

**Comment by SamSaffron** [comment]
this is real strange, you sure v8 is installed correctly on you ec2 install

**Comment by bdmac** [comment]
Well it worked some % of the time from sidekiq previously and seems to work 100% now that I'm running this one job in Resque instead of sidekiq. Also the v8 stuff works outside the context of a thread too on that box. Other than that I'm not sure how to tell if v8 is installed correctly. I don't believe we installed it ourselves; I think the gem handled that.



—
