### ISSUE TITLE
typed array such as Int32Array undefined 

### ISSUE THREAD

**Issue by itkin** [rubyjs/therubyracer#313]
Hello,

I was looking to execute some js library server side, but got this error "Int32Array is undefined"

Was wondering if there is any quick and easy possibility to add this constructor and its dependencies (tried to load some typedarray emulation libs found on the web but all what i've found so far break the code - which runs fine on modern browsers)

Thanks in advance !

**Comment by cowboyd** [comment]
This is not supported, but would love to add this feature.
