### ISSUE TITLE
Segmentation fault with libv8 3.16.14.5 on Travis / Codeship / Docker

### ISSUE THREAD

**Issue by tagliala** [rubyjs/therubyracer#316]
Hi,

I don't know if this is the right place to report the issue that I ran into.

Please take a look at these jobs:
https://travis-ci.org/diowa/twbs_less_rails/builds/35053004
https://travis-ci.org/diowa/twbs_less_rails/builds/35054020

The only things that change is the `libv8` version, from `3.16.14.3` to `3.16.14.5`.

I'm opening an issue on rubyracer because libv8's build passed on heroku while there is no recent build of therubyracer ran against libv8 3.16.14.5

You can check the datails of the failure in any of the jobs' builds:

```
/home/travis/.rvm/gems/ruby-1.9.3-p547/gems/therubyracer-0.12.1/lib/v8/function.rb:13: [BUG] Segmentation fault
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
```

Let me know if I should report this to travis

Everything is fine on my local machine (OSX 10.9.4)

**Comment by tagliala** [comment]
@thogg4 is this still an issue for you?

**Comment by lnikkila** [comment]
I’m getting this on OS X 10.10.3 even with libv8 3.16.14.7.

[Crash logs and Gemfile.lock on Gist.](https://gist.github.com/lnikkila/ecbe7bad30ababf6a3fa)

**Comment by cowboyd** [comment]
@ignisf What would you recommend, compiling with GCC 4.8?

**Comment by ignisf** [comment]
I could not manage to get to the bottom of this, I just compiled the binary on an Ubuntu 12.04 LTS and had no issues

**Comment by cowboyd** [comment]
Hmmmm, is there any way to track down which version of GCC `3.16.14.5` was compiled on?

**Comment by ignisf** [comment]
GCC 4.9.1/glibc 2.19 which was the current version for arch linux on September 8, 2014
