### ISSUE TITLE
TheRubyRacer 0.12.1 Segmentation Fault

### ISSUE THREAD

**Issue by luisincrespo** [rubyjs/therubyracer#317]
Hi there. I've configured my Rails app for using twitter-bootstrap-rails and they require a JS runtime such as therubyracer (which I chose) to work with. These are the gems I'm working with:

```
gem 'therubyracer',  platforms: :ruby
gem "less-rails"
gem "twitter-bootstrap-rails"
```

When I run my app I get the following error: 

```
.rvm/gems/ruby-2.1.2/gems/therubyracer-0.12.1/lib/v8/function.rb:13: [BUG] Segmentation fault at
0x00000000000000
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

Any fix?.

Thanks,

**Comment by HPrMeyer** [comment]
I am experiencing the exact problem trying a GitLab installation on a BananaPi
Versions:
libv8 3.16.14.7
therubyracer 1.12.1 (tried 1.12.0 before, no difference)
ruby: 2.1.5

the error I get:
command: sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:13: [BUG] Segmentation fault at 0x30c124
ruby 2.1.5p273 (2014-11-13 revision 48405) [armv7l-linux-eabihf]

-- Control frame information -----------------------------------------------
c:0079 p:---- s:0342 e:000341 CFUNC  :Call
c:0078 p:0022 s:0337 e:000336 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:13
c:0077 p:0006 s:0335 e:000334 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/error.rb:84 [FINISH]
c:0076 p:---- s:0331 e:000330 CFUNC  :call
c:0075 p:---- s:0329 e:000328 CFUNC  :TryCatch
c:0074 p:0015 s:0326 E:fffffd34 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/error.rb:83
c:0073 p:0033 s:0323 E:fffff514 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:13
c:0072 p:0024 s:0320 e:000319 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:206
c:0071 p:0009 s:0316 E:fffff7d4 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:11
c:0070 p:0016 s:0311 e:000310 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:19
c:0069 p:0021 s:0309 e:000308 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:248 [FINISH]
c:0068 p:---- s:0307 e:000306 CFUNC  :call
c:0067 p:---- s:0305 e:000304 CFUNC  :HandleScope
c:0066 p:0015 s:0302 E:fffff364 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:245 [FINISH]
c:0065 p:---- s:0300 e:000299 CFUNC  :call
c:0064 p:---- s:0298 e:000297 CFUNC  :Locker
c:0063 p:0041 s:0295 E:fffff878 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:244
c:0062 p:0018 s:0291 e:000290 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:204
c:0061 p:0009 s:0287 E:ffffff88 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:18
c:0060 p:0018 s:0283 e:000281 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:44
c:0059 p:0008 s:0279 e:000278 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:80 [FINISH]
c:0058 p:---- s:0276 e:000275 CFUNC  :call
c:0057 p:---- s:0274 e:000273 CFUNC  :Locker
c:0056 p:0023 s:0271 E:ffffdb8c METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78
c:0055 p:0007 s:0266 E:ffffe31c METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:42
c:0054 p:0087 s:0261 e:000260 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:57
c:0053 p:0033 s:0256 e:000255 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/coffee.rb:46
c:0052 p:0034 s:0250 e:000249 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103
c:0051 p:0025 s:0244 E:ffffddb8 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:197 [FINISH]
c:0050 p:---- s:0239 e:000238 CFUNC  :each
c:0049 p:0145 s:0236 E:ffffef84 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194
c:0048 p:0054 s:0225 e:000224 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12 [FINISH]
c:0047 p:---- s:0216 e:000215 CFUNC  :new
c:0046 p:0020 s:0210 e:000209 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:374
c:0045 p:0108 s:0208 e:000207 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:395
c:0044 p:0053 s:0202 e:000201 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:373
c:0043 p:0014 s:0196 e:000195 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94
c:0042 p:0060 s:0194 e:000193 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58
c:0041 p:0050 s:0188 e:000184 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93
c:0040 p:0140 s:0178 e:000177 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287
c:0039 p:0060 s:0170 e:000169 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61
c:0038 p:0029 s:0162 e:000161 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:16 [FINISH]
c:0037 p:---- s:0155 e:000154 CFUNC  :new
c:0036 p:0073 s:0149 e:000148 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377
c:0035 p:0014 s:0143 e:000142 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94
c:0034 p:0060 s:0141 e:000140 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58
c:0033 p:0050 s:0135 e:000131 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93
c:0032 p:0140 s:0125 e:000124 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287
c:0031 p:0060 s:0117 e:000116 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61
c:0030 p:0011 s:0109 e:000108 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211
c:0029 p:0021 s:0107 e:000106 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257
c:0028 p:0012 s:0103 e:000102 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210
c:0027 p:0009 s:0097 e:000096 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119 [FINISH]
c:0026 p:---- s:0092 e:000091 CFUNC  :each
c:0025 p:0051 s:0089 e:000088 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118
c:0024 p:0012 s:0084 e:000083 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61
c:0023 p:0036 s:0082 e:000081 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146
c:0022 p:0007 s:0077 e:000076 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60 [FINISH]
c:0021 p:---- s:0075 e:000074 CFUNC  :call
c:0020 p:0028 s:0070 e:000069 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240 [FINISH]
c:0019 p:---- s:0067 e:000066 CFUNC  :each
c:0018 p:0113 s:0064 e:000063 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235
c:0017 p:0075 s:0060 e:000059 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179
c:0016 p:0014 s:0058 e:000057 METHOD /usr/local/lib/ruby/2.1.0/monitor.rb:211
c:0015 p:0025 s:0055 e:000054 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172
c:0014 p:0036 s:0048 e:000047 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165
c:0013 p:0033 s:0043 e:000042 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150
c:0012 p:0009 s:0036 e:000035 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106 [FINISH]
c:0011 p:---- s:0033 e:000032 CFUNC  :each
c:0010 p:0039 s:0030 e:000029 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106
c:0009 p:0025 s:0028 e:000027 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115
c:0008 p:0007 s:0024 e:000023 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100
c:0007 p:0019 s:0021 e:000020 BLOCK  /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78
c:0006 p:0006 s:0019 e:000018 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176
c:0005 p:0007 s:0015 e:000014 METHOD /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75
c:0004 p:0040 s:0012 e:000011 TOP    /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0135 s:0006 E:fffffeb4 EVAL   /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23 [FINISH]
c:0001 p:0000 s:0002 E:fffff784 TOP    [FINISH]

/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:60:in `block (2 levels) in define'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:61:in `block (3 levels) in define'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:16:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/coffee.rb:46:in `evaluate'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:57:in `compile'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:42:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `Locker'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:78:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:80:in `block in lock'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/execjs-2.0.2/lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:18:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:204:in `enter'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:244:in `lock_scope_and_enter'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:244:in `Locker'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:244:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:245:in `block in lock_scope_and_enter'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:245:in `HandleScope'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:245:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:248:in `block (2 levels) in lock_scope_and_enter'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:19:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:11:in `methodcall'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/context.rb:206:in `enter'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:13:in `block in methodcall'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/error.rb:83:in `try'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/error.rb:83:in `TryCatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/error.rb:83:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/error.rb:84:in `block in try'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:13:in `block (2 levels) in methodcall'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/therubyracer-0.12.1/lib/v8/function.rb:13:in `Call'

**Comment by oceyral** [comment]
Same bug while installing Gitlab on arm, happens on all versions of ruby from 2.1.5 up to the 2.3.0dev snapshot.

Full log file available at https://bugs.ruby-lang.org/issues/10807

**Comment by Ch33f** [comment]
Same thing here. Tried to install Gitlab on a Raspberry Pi 2. (ARMv7)

**Comment by edouardb** [comment]
Same here. (ARMv7)

**Comment by dosire** [comment]
Is this bug related to https://github.com/gitlabhq/gitlabhq/issues/8809 ?

**Comment by dosire** [comment]
We're using https://github.com/gitlabhq/gitlabhq/issues/8809 to discuss this.

**Comment by maxlazio** [comment]
You can find the Raspberry Pi 2 package for GitLab on  Raspbian OS [here](https://about.gitlab.com/installation/).

**Comment by Karengc** [comment]
There's an official Omnibus package for the RPi2, see 'Omnibus package for Raspberry Pi 2' on https://about.gitlab.com/installation/

**Comment by rriemann** [comment]
This seems to be the relevant bug blocking Discourse Forum software running on ARM. Any progress on this issue? /cc @edouardb

**Comment by rriemann** [comment]
[stacktrace.txt](https://github.com/cowboyd/therubyracer/files/102469/stacktrace.txt)

@edouardb got a version that does not have this issue. Maybe it is possible to bisect to find the error?

**Comment by Dbz** [comment]
I'm commenting to help the google visibility of this issue. I've had seg fault issues on two rails apps (~ Rails 4.2) when dockerizing them. Upgrading libv8 and therubyracer seems to appease the seg fault gods.
