### ISSUE TITLE
can't install on gentoo

### ISSUE THREAD

**Issue by h0i** [rubyjs/therubyracer#319]
Trying to install on gentoo box but I get the following errors:

gem install therubyracer
Fetching: ref-1.0.5.gem (100%)
Successfully installed ref-1.0.5
Fetching: libv8-3.16.14.7-x86_64-linux.gem (100%)
Successfully installed libv8-3.16.14.7-x86_64-linux
Fetching: therubyracer-0.12.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing therubyracer:
    ERROR: Failed to build gem native extension.

```
/kunden/dir/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb
```

checking for main() in -lpthread... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling constants.cc
compiling heap.cc
compiling accessor.cc
compiling object.cc
compiling array.cc
compiling rr.cc
compiling string.cc
compiling date.cc
compiling invocation.cc
compiling value.cc
compiling handles.cc
compiling stack.cc
compiling gc.cc
compiling trycatch.cc
compiling init.cc
compiling backref.cc
compiling locker.cc
compiling exception.cc
compiling function.cc
compiling script.cc
compiling external.cc
compiling constraints.cc
compiling template.cc
compiling message.cc
compiling signature.cc
compiling v8.cc
compiling primitive.cc
compiling context.cc
linking shared-object v8/init.so
g++: /kunden/dir/.rvm/gems/ruby-2.1.2@project/gems/libv8-3.16.14.7-x86_64-linux/vendor/v8/out/ia32.release/obj.target/tools/gyp/libv8_base.a: No such file or directory
g++: /kunden/dir/.rvm/gems/ruby-2.1.2@project/gems/libv8-3.16.14.7-x86_64-linux/vendor/v8/out/ia32.release/obj.target/tools/gyp/libv8_snapshot.a: No such file or directory

Any ideas?

Thanks!

**Comment by judgetr** [comment]
i'm having the exact same issue, is there any update on this ?

**Comment by ignisf** [comment]
This will be fixed in libv8 4.5 by https://github.com/cowboyd/libv8/commit/3cbf1c3517ebd4aa447723713ee8ab2f542e14e9
